name: get_it_future_builder
description: Wait for your async `get_it` dependencies to be ready in the presentation layer.
version: 0.3.3
homepage: https://github.com/erayerdin/get_it_future_builder
repository: https://github.com/erayerdin/get_it_future_builder
issue_tracker: https://github.com/erayerdin/get_it_future_builder/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - widgets
  - ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ">=7.0.0 <8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=5.0.0 <7.0.0"
