name: get_it_future_builder
description: Wait for your async `get_it` dependencies to be ready in the presentation layer.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ">=7.0.0 <8.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
